blog/urls.py
from django.urls import path
from .views import blogListView, blogCreateView, blogDetailView, blogUpdateView, blogDeleteView

app_name = "blog"

urlpatterns = [
      path('', blogListView.as_view(), name="home"),
      path('create/', blogCreateView.as_view(), name="create"),
      path('<int:pk>/', blogDetailView.as_view(), name="detail"),
      path('<int:pk>/update/', blogUpdateView.as_view(), name="update"),
      path('<int:pk>/delete/', blogDeleteView.as_view(), name="delete")
]

core/urls.py
from turtle import home
from django.contrib import admin
from django.urls import path, include

from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name="home"),
    path('blog/', include('blog.urls', namespace='blog'))
]

blog/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=250)
    content = models.TextField()

    def __str__(self):
      return self.title

blog/forms.py
from django import forms

from .models import Post

class PostCreateForm(forms.ModelForm):
      class Meta:
            model=Post
            fields=('title', 'content')

blog/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic.base import View
from django.views.generic.edit import UpdateView, DeleteView
from .forms import PostCreateForm
from .models import Post
from django.urls import reverse_lazy

class blogListView(View):
      def get(self, request, *args, **kwargs):
            posts = Post.objects.all()
            context = {
                  'posts': posts
            }
            return render(request, 'blog_list.html', context)

class blogCreateView(View):
      def get(self, request, *args, **kwargs):
            form = PostCreateForm()
            context = {
                'form': form  
            }
            return render(request, 'blog_create.html', context)
      def post(self, request, *args, **kwargs):
            if request.method == "POST":
                  form = PostCreateForm(request.POST)
                  if form.is_valid():
                        title = form.cleaned_data.get('title')
                        content = form.cleaned_data.get('content')

                        p, created = Post.objects.get_or_create(title = title, content = content)
                        p.save()
                        return redirect('blog:home')
            context = {
                  
            }
            return render(request, 'blog_create.html', context)      

class blogDetailView(View):
      def get(self, request, pk,*args, **kwargs):
            post = get_object_or_404(Post, pk=pk)
            context = {
                  'post': post
            }
            return render(request, 'blog_detail.html', context)            

class blogUpdateView(UpdateView):
      model = Post
      fields = ['title', 'content']
      template_name = 'blog_update.html'
      def get_success_url(self):
            pk = self.kwargs['pk']
            return reverse_lazy('blog:detail', kwargs={'pk':pk})

class blogDeleteView(DeleteView):
      model = Post
      template_name = 'blog_delete.html'
      success_url = reverse_lazy('blog:home')            

core/views.py
from operator import imod
from django.views.generic import View
from django.shortcuts import render, redirect

class HomeView(View):
      def get(self, request, *args, **kwargs):
            context={

            }
            return render(request, 'index.html', context)

templates/base.html
{% load tailwind_tags %}
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      {% tailwind_css %}
      <title>Document</title>
</head>
<body>

      {% block content %}{% endblock content %}
      
</body>
</html>

templates/blog_create.html
<!DOCTYPE html>
<html>
      <head>
            <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <title>Crear post</title>
            <meta name="description" content="">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <link rel="stylesheet" href="">
      </head>
      <body>
            <form method="POST">
                  {% csrf_token %}
                  title{{form.title}}
                  <br>
                  content{{form.content}}
                  <button type="submit">Subir</button>
            </form>      
      </body>
</html>

templates/blog_delete.html
<!DOCTYPE html>
<html>
      <head>
            <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <title>Eliminar</title>
            <meta name="description" content="">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <link rel="stylesheet" href="">
      </head>
      <body>
            <form method="POST">
                  {% csrf_token %}
                  <h5>Eliminar? {{post.id}}</h5>
                  <h5>{{post.title}}</h5>
                  <h5>{{post.content}}</h5>
                  {{form}}
                  <button type="submit">Eliminar</button>
            </form>      
      </body>
</html>

templates/blog_detail.html
<!DOCTYPE html>
<html>
      <head>
            <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <title>DetailView</title>
            <meta name="description" content="">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <link rel="stylesheet" href="">
      </head>
      <body>
            <h4>
                  Numero: 
                  {{post.id}}
            </h4>
            <h4>
                  Titulo: 
                  {{post.title}}
            </h4>
            <h4>
                  Contenido: 
                  {{post.content}}
            </h4>
            <a href="{% url 'blog:update' post.id %}">Update</a>
            <a href="{% url 'blog:delete' post.id %}">Delete</a>
      </body>
</html>

templates/blog_list.html
<!DOCTYPE html>
<html>
      <head>
            <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <title>Lista de POSTS</title>
            <meta name="description" content="">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <link rel="stylesheet" href="">
      </head>
      <body>
            <h1>Hola, crea un post :D </h1>
            <br>
            {% for post in posts %}
                  <a href={% url 'blog:detail' post.id %}>{{post.id}}</a>
                  <h5>  Titulo:   
                        {{post.title}}
                  </h5>
                  <h5>      
                        Contenido: 
                        {{post.content}}      
                  </h5>
            {% endfor %}
            <br>
            <a href="{% url 'blog:create' %}">Click aqui</a>
      </body>
</html>

templates/blog_update.html
<!DOCTYPE html>
<html>
      <head>
            <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <title>Crear post</title>
            <meta name="description" content="">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <link rel="stylesheet" href="">
      </head>
      <body>
            <form method="POST">
                  {% csrf_token %}
                  title{{form.title}}
                  <br>
                  content{{form.content}}
                  <button type="submit">Actualizar</button>
            </form>      
      </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
      hola, visita mi blog aqui

      <a href="{% url 'blog:home' %}">ASA</a>
{% endblock content %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-grey-lightest font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>